// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API_KEY',
    appId: '1:56543977861:web:4ae96bedff60adb87624ec',
    messagingSenderId: '56543977861',
    projectId: 'mindthegap-1d0fd',
    authDomain: 'mindthegap-1d0fd.firebaseapp.com',
    storageBucket: 'mindthegap-1d0fd.firebasestorage.app',
    measurementId: 'G-4HRVLDH97S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV7dYzlr582Gc6ZhKU4oQOzQDNYafddTA',
    appId: '1:56543977861:android:94e7c0a4d039744b7624ec',
    messagingSenderId: '56543977861',
    projectId: 'mindthegap-1d0fd',
    storageBucket: 'mindthegap-1d0fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDaToFFR2_3iZ8cRwQPLy89uJo2RYnazc',
    appId: '1:56543977861:ios:c439d53237f5fe847624ec',
    messagingSenderId: '56543977861',
    projectId: 'mindthegap-1d0fd',
    storageBucket: 'mindthegap-1d0fd.firebasestorage.app',
    iosBundleId: 'com.example.mindTheGapV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDaToFFR2_3iZ8cRwQPLy89uJo2RYnazc',
    appId: '1:56543977861:ios:c439d53237f5fe847624ec',
    messagingSenderId: '56543977861',
    projectId: 'mindthegap-1d0fd',
    storageBucket: 'mindthegap-1d0fd.firebasestorage.app',
    iosBundleId: 'com.example.mindTheGapV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxwBxP1T0yB4RkcRixTK4Ud_653BmRBMs',
    appId: '1:56543977861:web:4ae96bedff60adb87624ec',
    messagingSenderId: '56543977861',
    projectId: 'mindthegap-1d0fd',
    authDomain: 'mindthegap-1d0fd.firebaseapp.com',
    storageBucket: 'mindthegap-1d0fd.firebasestorage.app',
    measurementId: 'G-4HRVLDH97S',
  );

}
